force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>Stores job postings and criteria for candidate matching.</description>
    <label>Job</label>
    <pluralLabel>Jobs</pluralLabel>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AvailableJobsAction.cls
public class AvailableJobsAction {
    public class Request {
        @InvocableVariable(label='Search Filter' description='Optional filter to search jobs by keyword' required=false)
        public String searchFilter;
    }

    @InvocableMethod(label='List Jobs' description='Returns a list of open job records.')
    public static List<List<Job__c>> getJobs(List<Request> requests) {

        if (requests == null || requests.isEmpty() || String.isBlank(requests[0].searchFilter)) {
            List<Job__c> jobs = [
                SELECT Id, Name, Description__c, Role__c, Data__c
                FROM Job__c
                LIMIT 50
            ];
            return new List<List<Job__c>>{ jobs };
        }
        else{
            String searchFilter = requests[0].searchFilter;
            List<Job__c> jobs = [
                SELECT Id, Name, Description__c, Role__c, Data__c
                FROM Job__c
                WHERE Name LIKE :('%' + searchFilter + '%')
                LIMIT 50
            ];
            return new List<List<Job__c>>{ jobs };
        }
    }
}